/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _E2SM_GNB_NRT_ASN_CONSTANT_H
#define _E2SM_GNB_NRT_ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define E2SM_GNB_NRT_maxofCellinRAN (16384)
#define E2SM_GNB_NRT_maxNoOfNeighbours (1024)
#define E2SM_GNB_NRT_maxofRANParameters (255)
#define E2SM_GNB_NRT_maxofRICstyles (63)
#define min_val_E2SM_GNB_NRT_RANparameter_ID (0)
#define max_val_E2SM_GNB_NRT_RANparameter_ID (255)


#ifdef __cplusplus
}
#endif

#endif /* _E2SM_GNB_NRT_ASN_CONSTANT_H */
