/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "/local/setup/srslte-ric/srsenb/src/ric/messages/asn1/e2sm-kpm-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/setup/srslte-ric/build/srsenb/src/ric/messages/E2SM-KPM/`
 */

#include "E2SM_KPM_OCUUP-PF-Container.h"

#include "E2SM_KPM_PF-ContainerListItem.h"
static int
memb_E2SM_KPM_pf_ContainerList_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 3)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_E2SM_KPM_pf_ContainerList_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  3 }	/* (SIZE(1..3)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2SM_KPM_pf_ContainerList_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  3 }	/* (SIZE(1..3)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_E2SM_KPM_pf_ContainerList_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2SM_KPM_PF_ContainerListItem,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2SM_KPM_pf_ContainerList_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_E2SM_KPM_pf_ContainerList_specs_3 = {
	sizeof(struct E2SM_KPM_OCUUP_PF_Container__pf_ContainerList),
	offsetof(struct E2SM_KPM_OCUUP_PF_Container__pf_ContainerList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_E2SM_KPM_pf_ContainerList_3 = {
	"pf-ContainerList",
	"pf-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2SM_KPM_pf_ContainerList_tags_3,
	sizeof(asn_DEF_E2SM_KPM_pf_ContainerList_tags_3)
		/sizeof(asn_DEF_E2SM_KPM_pf_ContainerList_tags_3[0]) - 1, /* 1 */
	asn_DEF_E2SM_KPM_pf_ContainerList_tags_3,	/* Same as above */
	sizeof(asn_DEF_E2SM_KPM_pf_ContainerList_tags_3)
		/sizeof(asn_DEF_E2SM_KPM_pf_ContainerList_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_E2SM_KPM_pf_ContainerList_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_E2SM_KPM_pf_ContainerList_3,
	1,	/* Single element */
	&asn_SPC_E2SM_KPM_pf_ContainerList_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2SM_KPM_OCUUP_PF_Container_1[] = {
	{ ATF_POINTER, 1, offsetof(struct E2SM_KPM_OCUUP_PF_Container, gNB_CU_UP_Name),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_KPM_GNB_CU_UP_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gNB-CU-UP-Name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_KPM_OCUUP_PF_Container, pf_ContainerList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_E2SM_KPM_pf_ContainerList_3,
		0,
		{ 0, &asn_PER_memb_E2SM_KPM_pf_ContainerList_constr_3,  memb_E2SM_KPM_pf_ContainerList_constraint_1 },
		0, 0, /* No default value */
		"pf-ContainerList"
		},
};
static const int asn_MAP_E2SM_KPM_OCUUP_PF_Container_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_E2SM_KPM_OCUUP_PF_Container_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_KPM_OCUUP_PF_Container_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gNB-CU-UP-Name */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* pf-ContainerList */
};
asn_SEQUENCE_specifics_t asn_SPC_E2SM_KPM_OCUUP_PF_Container_specs_1 = {
	sizeof(struct E2SM_KPM_OCUUP_PF_Container),
	offsetof(struct E2SM_KPM_OCUUP_PF_Container, _asn_ctx),
	asn_MAP_E2SM_KPM_OCUUP_PF_Container_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_E2SM_KPM_OCUUP_PF_Container_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_KPM_OCUUP_PF_Container = {
	"OCUUP-PF-Container",
	"OCUUP-PF-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_KPM_OCUUP_PF_Container_tags_1,
	sizeof(asn_DEF_E2SM_KPM_OCUUP_PF_Container_tags_1)
		/sizeof(asn_DEF_E2SM_KPM_OCUUP_PF_Container_tags_1[0]), /* 1 */
	asn_DEF_E2SM_KPM_OCUUP_PF_Container_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_KPM_OCUUP_PF_Container_tags_1)
		/sizeof(asn_DEF_E2SM_KPM_OCUUP_PF_Container_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_KPM_OCUUP_PF_Container_1,
	2,	/* Elements count */
	&asn_SPC_E2SM_KPM_OCUUP_PF_Container_specs_1	/* Additional specs */
};

