/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "/local/setup/srslte-ric/srsenb/src/ric/messages/asn1/e2sm-kpm-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/setup/srslte-ric/build/srsenb/src/ric/messages/E2SM-KPM/`
 */

#include "E2SM_KPM_RIC-Style-Type.h"

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_E2SM_KPM_RIC_Style_Type_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
asn_TYPE_descriptor_t asn_DEF_E2SM_KPM_RIC_Style_Type = {
	"RIC-Style-Type",
	"RIC-Style-Type",
	&asn_OP_NativeInteger,
	asn_DEF_E2SM_KPM_RIC_Style_Type_tags_1,
	sizeof(asn_DEF_E2SM_KPM_RIC_Style_Type_tags_1)
		/sizeof(asn_DEF_E2SM_KPM_RIC_Style_Type_tags_1[0]), /* 1 */
	asn_DEF_E2SM_KPM_RIC_Style_Type_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_KPM_RIC_Style_Type_tags_1)
		/sizeof(asn_DEF_E2SM_KPM_RIC_Style_Type_tags_1[0]), /* 1 */
	{ 0, 0, NativeInteger_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

