/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "/local/setup/srslte-ric/srsenb/src/ric/messages/asn1/e2sm-kpm-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/setup/srslte-ric/build/srsenb/src/ric/messages/E2SM-KPM/`
 */

#include "E2SM_KPM_SNSSAI.h"

static int
memb_E2SM_KPM_sST_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_E2SM_KPM_sD_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_E2SM_KPM_sST_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  1,  1 }	/* (SIZE(1..1)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2SM_KPM_sD_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  3,  3 }	/* (SIZE(3..3)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_E2SM_KPM_SNSSAI_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_KPM_SNSSAI, sST),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, &asn_PER_memb_E2SM_KPM_sST_constr_2,  memb_E2SM_KPM_sST_constraint_1 },
		0, 0, /* No default value */
		"sST"
		},
	{ ATF_POINTER, 1, offsetof(struct E2SM_KPM_SNSSAI, sD),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, &asn_PER_memb_E2SM_KPM_sD_constr_3,  memb_E2SM_KPM_sD_constraint_1 },
		0, 0, /* No default value */
		"sD"
		},
};
static const int asn_MAP_E2SM_KPM_SNSSAI_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_E2SM_KPM_SNSSAI_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_KPM_SNSSAI_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sST */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* sD */
};
asn_SEQUENCE_specifics_t asn_SPC_E2SM_KPM_SNSSAI_specs_1 = {
	sizeof(struct E2SM_KPM_SNSSAI),
	offsetof(struct E2SM_KPM_SNSSAI, _asn_ctx),
	asn_MAP_E2SM_KPM_SNSSAI_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_E2SM_KPM_SNSSAI_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_KPM_SNSSAI = {
	"SNSSAI",
	"SNSSAI",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_KPM_SNSSAI_tags_1,
	sizeof(asn_DEF_E2SM_KPM_SNSSAI_tags_1)
		/sizeof(asn_DEF_E2SM_KPM_SNSSAI_tags_1[0]), /* 1 */
	asn_DEF_E2SM_KPM_SNSSAI_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_KPM_SNSSAI_tags_1)
		/sizeof(asn_DEF_E2SM_KPM_SNSSAI_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_KPM_SNSSAI_1,
	2,	/* Elements count */
	&asn_SPC_E2SM_KPM_SNSSAI_specs_1	/* Additional specs */
};

