/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "./e2ap-v01.01.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D E2AP-v01.01/`
 */

#ifndef	_E2AP_E2nodeComponentConfigUpdateAck_H_
#define	_E2AP_E2nodeComponentConfigUpdateAck_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2AP_E2nodeComponentConfigUpdateAck__updateOutcome {
	E2AP_E2nodeComponentConfigUpdateAck__updateOutcome_success	= 0,
	E2AP_E2nodeComponentConfigUpdateAck__updateOutcome_failure	= 1
	/*
	 * Enumeration is extensible
	 */
} e_E2AP_E2nodeComponentConfigUpdateAck__updateOutcome;

/* Forward declarations */
struct E2AP_Cause;

/* E2AP_E2nodeComponentConfigUpdateAck */
typedef struct E2AP_E2nodeComponentConfigUpdateAck {
	long	 updateOutcome;
	struct E2AP_Cause	*failureCause;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_E2nodeComponentConfigUpdateAck_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_E2AP_updateOutcome_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_E2AP_E2nodeComponentConfigUpdateAck;
extern asn_SEQUENCE_specifics_t asn_SPC_E2AP_E2nodeComponentConfigUpdateAck_specs_1;
extern asn_TYPE_member_t asn_MBR_E2AP_E2nodeComponentConfigUpdateAck_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _E2AP_E2nodeComponentConfigUpdateAck_H_ */
#include "asn_internal.h"
