/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _E2AP_ASN_CONSTANT_H
#define _E2AP_ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define min_val_E2AP_GNB_CU_UP_ID (0)
#define max_val_E2AP_GNB_CU_UP_ID (68719476735)
#define min_val_E2AP_GNB_DU_ID (0)
#define max_val_E2AP_GNB_DU_ID (68719476735)
#define min_val_E2AP_RANfunctionID (0)
#define max_val_E2AP_RANfunctionID (4095)
#define min_val_E2AP_RANfunctionRevision (0)
#define max_val_E2AP_RANfunctionRevision (4095)
#define min_val_E2AP_RICactionID (0)
#define max_val_E2AP_RICactionID (255)
#define min_val_E2AP_RICindicationSN (0)
#define max_val_E2AP_RICindicationSN (65535)
#define min_val_E2AP_ProcedureCode (0)
#define max_val_E2AP_ProcedureCode (255)
#define min_val_E2AP_ProtocolIE_ID (0)
#define max_val_E2AP_ProtocolIE_ID (65535)
#define E2AP_maxProtocolIEs (65535)
#define E2AP_maxnoofErrors (256)
#define E2AP_maxofE2nodeComponents (1024)
#define E2AP_maxofRANfunctionID (256)
#define E2AP_maxofRICactionID (16)
#define E2AP_maxofTNLA (32)


#ifdef __cplusplus
}
#endif

#endif /* _E2AP_ASN_CONSTANT_H */
