/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "./e2ap-v01.01.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D E2AP-v01.01/`
 */

#ifndef	_E2AP_RANfunctionOID_H_
#define	_E2AP_RANfunctionOID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PrintableString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* E2AP_RANfunctionOID */
typedef PrintableString_t	 E2AP_RANfunctionOID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E2AP_RANfunctionOID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_RANfunctionOID;
asn_struct_free_f E2AP_RANfunctionOID_free;
asn_struct_print_f E2AP_RANfunctionOID_print;
asn_constr_check_f E2AP_RANfunctionOID_constraint;
ber_type_decoder_f E2AP_RANfunctionOID_decode_ber;
der_type_encoder_f E2AP_RANfunctionOID_encode_der;
xer_type_decoder_f E2AP_RANfunctionOID_decode_xer;
xer_type_encoder_f E2AP_RANfunctionOID_encode_xer;
per_type_decoder_f E2AP_RANfunctionOID_decode_uper;
per_type_encoder_f E2AP_RANfunctionOID_encode_uper;
per_type_decoder_f E2AP_RANfunctionOID_decode_aper;
per_type_encoder_f E2AP_RANfunctionOID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E2AP_RANfunctionOID_H_ */
#include "asn_internal.h"
