/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _E2SM_KPM_ASN_CONSTANT_H
#define _E2SM_KPM_ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define min_val_E2SM_KPM_GNB_CU_UP_ID (0)
#define max_val_E2SM_KPM_GNB_CU_UP_ID (68719476735)
#define min_val_E2SM_KPM_GNB_DU_ID (0)
#define max_val_E2SM_KPM_GNB_DU_ID (68719476735)
#define E2SM_KPM_maxofMessageProtocolTests (15)
#define E2SM_KPM_maxofRICstyles (63)
#define E2SM_KPM_maxnoofQCI (256)
#define E2SM_KPM_maxnoofQoSFlows (64)
#define E2SM_KPM_maxnoofSliceItems (1024)
#define E2SM_KPM_maxnoofContainerListItems (3)
#define E2SM_KPM_maxCellingNBDU (512)
#define E2SM_KPM_maxofContainers (8)
#define E2SM_KPM_maxPLMN (12)


#ifdef __cplusplus
}
#endif

#endif /* _E2SM_KPM_ASN_CONSTANT_H */
