/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "/local/setup/srslte-ric/srsenb/src/ric/messages/asn1/e2sm-kpm-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/setup/srslte-ric/build/srsenb/src/ric/messages/E2SM-KPM/`
 */

#ifndef	_E2SM_KPM_RT_Period_IE_H_
#define	_E2SM_KPM_RT_Period_IE_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2SM_KPM_RT_Period_IE {
	E2SM_KPM_RT_Period_IE_ms10	= 0,
	E2SM_KPM_RT_Period_IE_ms20	= 1,
	E2SM_KPM_RT_Period_IE_ms32	= 2,
	E2SM_KPM_RT_Period_IE_ms40	= 3,
	E2SM_KPM_RT_Period_IE_ms60	= 4,
	E2SM_KPM_RT_Period_IE_ms64	= 5,
	E2SM_KPM_RT_Period_IE_ms70	= 6,
	E2SM_KPM_RT_Period_IE_ms80	= 7,
	E2SM_KPM_RT_Period_IE_ms128	= 8,
	E2SM_KPM_RT_Period_IE_ms160	= 9,
	E2SM_KPM_RT_Period_IE_ms256	= 10,
	E2SM_KPM_RT_Period_IE_ms320	= 11,
	E2SM_KPM_RT_Period_IE_ms512	= 12,
	E2SM_KPM_RT_Period_IE_ms640	= 13,
	E2SM_KPM_RT_Period_IE_ms1024	= 14,
	E2SM_KPM_RT_Period_IE_ms1280	= 15,
	E2SM_KPM_RT_Period_IE_ms2048	= 16,
	E2SM_KPM_RT_Period_IE_ms2560	= 17,
	E2SM_KPM_RT_Period_IE_ms5120	= 18,
	E2SM_KPM_RT_Period_IE_ms10240	= 19
	/*
	 * Enumeration is extensible
	 */
} e_E2SM_KPM_RT_Period_IE;

/* E2SM_KPM_RT-Period-IE */
typedef long	 E2SM_KPM_RT_Period_IE_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E2SM_KPM_RT_Period_IE_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E2SM_KPM_RT_Period_IE;
extern const asn_INTEGER_specifics_t asn_SPC_E2SM_KPM_RT_Period_IE_specs_1;
asn_struct_free_f E2SM_KPM_RT_Period_IE_free;
asn_struct_print_f E2SM_KPM_RT_Period_IE_print;
asn_constr_check_f E2SM_KPM_RT_Period_IE_constraint;
ber_type_decoder_f E2SM_KPM_RT_Period_IE_decode_ber;
der_type_encoder_f E2SM_KPM_RT_Period_IE_encode_der;
xer_type_decoder_f E2SM_KPM_RT_Period_IE_decode_xer;
xer_type_encoder_f E2SM_KPM_RT_Period_IE_encode_xer;
per_type_decoder_f E2SM_KPM_RT_Period_IE_decode_uper;
per_type_encoder_f E2SM_KPM_RT_Period_IE_encode_uper;
per_type_decoder_f E2SM_KPM_RT_Period_IE_decode_aper;
per_type_encoder_f E2SM_KPM_RT_Period_IE_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_KPM_RT_Period_IE_H_ */
#include "asn_internal.h"
