/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "/local/setup/srslte-ric/srsenb/src/ric/messages/asn1/e2sm-kpm-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/setup/srslte-ric/build/srsenb/src/ric/messages/E2SM-KPM/`
 */

#include "E2SM_KPM_PerQCIReportListItemFormat.h"

static int
memb_E2SM_KPM_qci_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_E2SM_KPM_pDCPBytesDL_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const INTEGER_t *st = (const INTEGER_t *)sptr;
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(asn_INTEGER2long(st, &value)) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value too large (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((value >= 0 && value <= 10000000000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_E2SM_KPM_pDCPBytesUL_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const INTEGER_t *st = (const INTEGER_t *)sptr;
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(asn_INTEGER2long(st, &value)) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value too large (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((value >= 0 && value <= 10000000000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_E2SM_KPM_qci_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2SM_KPM_pDCPBytesDL_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  34, -1,  0,  10000000000 }	/* (0..10000000000,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2SM_KPM_pDCPBytesUL_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  34, -1,  0,  10000000000 }	/* (0..10000000000,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_E2SM_KPM_PerQCIReportListItemFormat_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_KPM_PerQCIReportListItemFormat, qci),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_E2SM_KPM_qci_constr_2,  memb_E2SM_KPM_qci_constraint_1 },
		0, 0, /* No default value */
		"qci"
		},
	{ ATF_POINTER, 2, offsetof(struct E2SM_KPM_PerQCIReportListItemFormat, pDCPBytesDL),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,
		{ 0, &asn_PER_memb_E2SM_KPM_pDCPBytesDL_constr_3,  memb_E2SM_KPM_pDCPBytesDL_constraint_1 },
		0, 0, /* No default value */
		"pDCPBytesDL"
		},
	{ ATF_POINTER, 1, offsetof(struct E2SM_KPM_PerQCIReportListItemFormat, pDCPBytesUL),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,
		{ 0, &asn_PER_memb_E2SM_KPM_pDCPBytesUL_constr_4,  memb_E2SM_KPM_pDCPBytesUL_constraint_1 },
		0, 0, /* No default value */
		"pDCPBytesUL"
		},
};
static const int asn_MAP_E2SM_KPM_PerQCIReportListItemFormat_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_E2SM_KPM_PerQCIReportListItemFormat_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_KPM_PerQCIReportListItemFormat_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* qci */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pDCPBytesDL */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* pDCPBytesUL */
};
asn_SEQUENCE_specifics_t asn_SPC_E2SM_KPM_PerQCIReportListItemFormat_specs_1 = {
	sizeof(struct E2SM_KPM_PerQCIReportListItemFormat),
	offsetof(struct E2SM_KPM_PerQCIReportListItemFormat, _asn_ctx),
	asn_MAP_E2SM_KPM_PerQCIReportListItemFormat_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_E2SM_KPM_PerQCIReportListItemFormat_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_KPM_PerQCIReportListItemFormat = {
	"PerQCIReportListItemFormat",
	"PerQCIReportListItemFormat",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_KPM_PerQCIReportListItemFormat_tags_1,
	sizeof(asn_DEF_E2SM_KPM_PerQCIReportListItemFormat_tags_1)
		/sizeof(asn_DEF_E2SM_KPM_PerQCIReportListItemFormat_tags_1[0]), /* 1 */
	asn_DEF_E2SM_KPM_PerQCIReportListItemFormat_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_KPM_PerQCIReportListItemFormat_tags_1)
		/sizeof(asn_DEF_E2SM_KPM_PerQCIReportListItemFormat_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_KPM_PerQCIReportListItemFormat_1,
	3,	/* Elements count */
	&asn_SPC_E2SM_KPM_PerQCIReportListItemFormat_specs_1	/* Additional specs */
};

