/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-gNB-NRT-IEs"
 * 	found in "/local/mnt/openairinterface5g/openair2/RIC_AGENT/MESSAGES/ASN1/R01/e2sm-gNB-NRT-v401.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/mnt/openairinterface5g/cmake_targets/ran_build/build/CMakeFiles/E2SM-GNB-NRT/`
 */

#include "E2SM_GNB_NRT_RIC-Format-Type.h"

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_E2SM_GNB_NRT_RIC_Format_Type_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
asn_TYPE_descriptor_t asn_DEF_E2SM_GNB_NRT_RIC_Format_Type = {
	"RIC-Format-Type",
	"RIC-Format-Type",
	&asn_OP_NativeInteger,
	asn_DEF_E2SM_GNB_NRT_RIC_Format_Type_tags_1,
	sizeof(asn_DEF_E2SM_GNB_NRT_RIC_Format_Type_tags_1)
		/sizeof(asn_DEF_E2SM_GNB_NRT_RIC_Format_Type_tags_1[0]), /* 1 */
	asn_DEF_E2SM_GNB_NRT_RIC_Format_Type_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_GNB_NRT_RIC_Format_Type_tags_1)
		/sizeof(asn_DEF_E2SM_GNB_NRT_RIC_Format_Type_tags_1[0]), /* 1 */
	{ 0, 0, NativeInteger_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

