/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-gNB-NRT-IEs"
 * 	found in "/local/mnt/openairinterface5g/openair2/RIC_AGENT/MESSAGES/ASN1/R01/e2sm-gNB-NRT-v401.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/mnt/openairinterface5g/cmake_targets/ran_build/build/CMakeFiles/E2SM-GNB-NRT/`
 */

#include "E2SM_GNB_NRT_RIC-ControlStyle-List.h"

asn_TYPE_member_t asn_MBR_E2SM_GNB_NRT_RIC_ControlStyle_List_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_GNB_NRT_RIC_ControlStyle_List, ric_ControlStyle_Type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_GNB_NRT_RIC_Style_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-ControlStyle-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_GNB_NRT_RIC_ControlStyle_List, ric_ControlStyle_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_GNB_NRT_RIC_Style_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-ControlStyle-Name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_GNB_NRT_RIC_ControlStyle_List, ric_ControlHeaderFormat_Type),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_GNB_NRT_RIC_Format_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-ControlHeaderFormat-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_GNB_NRT_RIC_ControlStyle_List, ric_ControlMessageFormat_Type),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_GNB_NRT_RIC_Format_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-ControlMessageFormat-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_GNB_NRT_RIC_ControlStyle_List, ric_CallProcessIDFormat_Type),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_GNB_NRT_RIC_Format_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-CallProcessIDFormat-Type"
		},
};
static const ber_tlv_tag_t asn_DEF_E2SM_GNB_NRT_RIC_ControlStyle_List_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_GNB_NRT_RIC_ControlStyle_List_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ric-ControlStyle-Type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ric-ControlStyle-Name */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ric-ControlHeaderFormat-Type */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ric-ControlMessageFormat-Type */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* ric-CallProcessIDFormat-Type */
};
asn_SEQUENCE_specifics_t asn_SPC_E2SM_GNB_NRT_RIC_ControlStyle_List_specs_1 = {
	sizeof(struct E2SM_GNB_NRT_RIC_ControlStyle_List),
	offsetof(struct E2SM_GNB_NRT_RIC_ControlStyle_List, _asn_ctx),
	asn_MAP_E2SM_GNB_NRT_RIC_ControlStyle_List_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_GNB_NRT_RIC_ControlStyle_List = {
	"RIC-ControlStyle-List",
	"RIC-ControlStyle-List",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_GNB_NRT_RIC_ControlStyle_List_tags_1,
	sizeof(asn_DEF_E2SM_GNB_NRT_RIC_ControlStyle_List_tags_1)
		/sizeof(asn_DEF_E2SM_GNB_NRT_RIC_ControlStyle_List_tags_1[0]), /* 1 */
	asn_DEF_E2SM_GNB_NRT_RIC_ControlStyle_List_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_GNB_NRT_RIC_ControlStyle_List_tags_1)
		/sizeof(asn_DEF_E2SM_GNB_NRT_RIC_ControlStyle_List_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_GNB_NRT_RIC_ControlStyle_List_1,
	5,	/* Elements count */
	&asn_SPC_E2SM_GNB_NRT_RIC_ControlStyle_List_specs_1	/* Additional specs */
};

