/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-NI-IEs"
 * 	found in "/local/mnt/openairinterface5g/openair2/RIC_AGENT/MESSAGES/ASN1/R01/e2sm-ni-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/mnt/openairinterface5g/cmake_targets/ran_build/build/CMakeFiles/E2SM-NI/`
 */

#include "E2SM_NI_NI-Identifier.h"

asn_per_constraints_t asn_PER_type_E2SM_NI_NI_Identifier_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }	/* (0..4,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_E2SM_NI_NI_Identifier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_NI_NI_Identifier, choice.global_eNB_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_NI_Global_eNB_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"global-eNB-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_NI_NI_Identifier, choice.global_en_gNB_ID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_NI_Global_en_gNB_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"global-en-gNB-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_NI_NI_Identifier, choice.global_ng_RAN_ID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_E2SM_NI_Global_ng_RAN_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"global-ng-RAN-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_NI_NI_Identifier, choice.global_gNB_DU_ID),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_NI_Global_gNB_DU_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"global-gNB-DU-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_NI_NI_Identifier, choice.global_gNB_CU_UP_ID),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_NI_Global_gNB_CU_UP_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"global-gNB-CU-UP-ID"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_NI_NI_Identifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* global-eNB-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* global-en-gNB-ID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* global-ng-RAN-ID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* global-gNB-DU-ID */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* global-gNB-CU-UP-ID */
};
asn_CHOICE_specifics_t asn_SPC_E2SM_NI_NI_Identifier_specs_1 = {
	sizeof(struct E2SM_NI_NI_Identifier),
	offsetof(struct E2SM_NI_NI_Identifier, _asn_ctx),
	offsetof(struct E2SM_NI_NI_Identifier, present),
	sizeof(((struct E2SM_NI_NI_Identifier *)0)->present),
	asn_MAP_E2SM_NI_NI_Identifier_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	5	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_NI_NI_Identifier = {
	"NI-Identifier",
	"NI-Identifier",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_E2SM_NI_NI_Identifier_constr_1, CHOICE_constraint },
	asn_MBR_E2SM_NI_NI_Identifier_1,
	5,	/* Elements count */
	&asn_SPC_E2SM_NI_NI_Identifier_specs_1	/* Additional specs */
};

