/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-NI-IEs"
 * 	found in "/local/mnt/openairinterface5g/openair2/RIC_AGENT/MESSAGES/ASN1/R01/e2sm-ni-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/mnt/openairinterface5g/cmake_targets/ran_build/build/CMakeFiles/E2SM-NI/`
 */

#ifndef	_E2SM_NI_NI_MessageTypeNG_H_
#define	_E2SM_NI_NI_MessageTypeNG_H_


#include "asn_application.h"

/* Including external dependencies */
#include "E2SM_NI_NI-MessageTypeApproach1.h"

#ifdef __cplusplus
extern "C" {
#endif

/* E2SM_NI_NI-MessageTypeNG */
typedef E2SM_NI_NI_MessageTypeApproach1_t	 E2SM_NI_NI_MessageTypeNG_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_NI_NI_MessageTypeNG;
asn_struct_free_f E2SM_NI_NI_MessageTypeNG_free;
asn_struct_print_f E2SM_NI_NI_MessageTypeNG_print;
asn_constr_check_f E2SM_NI_NI_MessageTypeNG_constraint;
ber_type_decoder_f E2SM_NI_NI_MessageTypeNG_decode_ber;
der_type_encoder_f E2SM_NI_NI_MessageTypeNG_encode_der;
xer_type_decoder_f E2SM_NI_NI_MessageTypeNG_decode_xer;
xer_type_encoder_f E2SM_NI_NI_MessageTypeNG_encode_xer;
per_type_decoder_f E2SM_NI_NI_MessageTypeNG_decode_uper;
per_type_encoder_f E2SM_NI_NI_MessageTypeNG_encode_uper;
per_type_decoder_f E2SM_NI_NI_MessageTypeNG_decode_aper;
per_type_encoder_f E2SM_NI_NI_MessageTypeNG_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_NI_NI_MessageTypeNG_H_ */
#include "asn_internal.h"
