/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-NI-IEs"
 * 	found in "/local/mnt/openairinterface5g/openair2/RIC_AGENT/MESSAGES/ASN1/R01/e2sm-ni-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/mnt/openairinterface5g/cmake_targets/ran_build/build/CMakeFiles/E2SM-NI/`
 */

#include "E2SM_NI_E2SM-NI-ControlHeader-Format1.h"

asn_TYPE_member_t asn_MBR_E2SM_NI_E2SM_NI_ControlHeader_Format1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_NI_E2SM_NI_ControlHeader_Format1, interface_type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_NI_NI_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"interface-type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_NI_E2SM_NI_ControlHeader_Format1, interface_ID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_E2SM_NI_NI_Identifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"interface-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_NI_E2SM_NI_ControlHeader_Format1, interface_Direction),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_NI_NI_Direction,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"interface-Direction"
		},
	{ ATF_POINTER, 1, offsetof(struct E2SM_NI_E2SM_NI_ControlHeader_Format1, ric_Control_Message_Priority),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_NI_RIC_Control_Message_Priority,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-Control-Message-Priority"
		},
};
static const int asn_MAP_E2SM_NI_E2SM_NI_ControlHeader_Format1_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_E2SM_NI_E2SM_NI_ControlHeader_Format1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_NI_E2SM_NI_ControlHeader_Format1_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* interface-type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* interface-ID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* interface-Direction */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* ric-Control-Message-Priority */
};
asn_SEQUENCE_specifics_t asn_SPC_E2SM_NI_E2SM_NI_ControlHeader_Format1_specs_1 = {
	sizeof(struct E2SM_NI_E2SM_NI_ControlHeader_Format1),
	offsetof(struct E2SM_NI_E2SM_NI_ControlHeader_Format1, _asn_ctx),
	asn_MAP_E2SM_NI_E2SM_NI_ControlHeader_Format1_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_E2SM_NI_E2SM_NI_ControlHeader_Format1_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_NI_E2SM_NI_ControlHeader_Format1 = {
	"E2SM-NI-ControlHeader-Format1",
	"E2SM-NI-ControlHeader-Format1",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_NI_E2SM_NI_ControlHeader_Format1_tags_1,
	sizeof(asn_DEF_E2SM_NI_E2SM_NI_ControlHeader_Format1_tags_1)
		/sizeof(asn_DEF_E2SM_NI_E2SM_NI_ControlHeader_Format1_tags_1[0]), /* 1 */
	asn_DEF_E2SM_NI_E2SM_NI_ControlHeader_Format1_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_NI_E2SM_NI_ControlHeader_Format1_tags_1)
		/sizeof(asn_DEF_E2SM_NI_E2SM_NI_ControlHeader_Format1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_NI_E2SM_NI_ControlHeader_Format1_1,
	4,	/* Elements count */
	&asn_SPC_E2SM_NI_E2SM_NI_ControlHeader_Format1_specs_1	/* Additional specs */
};

