/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-NI-IEs"
 * 	found in "/local/mnt/openairinterface5g/openair2/RIC_AGENT/MESSAGES/ASN1/R01/e2sm-ni-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/mnt/openairinterface5g/cmake_targets/ran_build/build/CMakeFiles/E2SM-NI/`
 */

#ifndef	_E2SM_NI_Criticality_H_
#define	_E2SM_NI_Criticality_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2SM_NI_Criticality {
	E2SM_NI_Criticality_reject	= 0,
	E2SM_NI_Criticality_ignore	= 1,
	E2SM_NI_Criticality_notify	= 2
} e_E2SM_NI_Criticality;

/* E2SM_NI_Criticality */
typedef long	 E2SM_NI_Criticality_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_NI_Criticality;
asn_struct_free_f E2SM_NI_Criticality_free;
asn_struct_print_f E2SM_NI_Criticality_print;
asn_constr_check_f E2SM_NI_Criticality_constraint;
ber_type_decoder_f E2SM_NI_Criticality_decode_ber;
der_type_encoder_f E2SM_NI_Criticality_encode_der;
xer_type_decoder_f E2SM_NI_Criticality_decode_xer;
xer_type_encoder_f E2SM_NI_Criticality_encode_xer;
per_type_decoder_f E2SM_NI_Criticality_decode_uper;
per_type_encoder_f E2SM_NI_Criticality_encode_uper;
per_type_decoder_f E2SM_NI_Criticality_decode_aper;
per_type_encoder_f E2SM_NI_Criticality_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_NI_Criticality_H_ */
#include "asn_internal.h"
