/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-NI-IEs"
 * 	found in "/local/mnt/openairinterface5g/openair2/RIC_AGENT/MESSAGES/ASN1/R01/e2sm-ni-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/mnt/openairinterface5g/cmake_targets/ran_build/build/CMakeFiles/E2SM-NI/`
 */

#ifndef	_E2SM_NI_E2SM_NI_RANfunction_Item_H_
#define	_E2SM_NI_E2SM_NI_RANfunction_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "E2SM_NI_NI-Type.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E2SM_NI_RIC_EventTriggerStyle_List;
struct E2SM_NI_RIC_ReportStyle_List;
struct E2SM_NI_RIC_InsertStyle_List;
struct E2SM_NI_RIC_ControlStyle_List;
struct E2SM_NI_RIC_PolicyStyle_List;

/* E2SM_NI_E2SM-NI-RANfunction-Item */
typedef struct E2SM_NI_E2SM_NI_RANfunction_Item {
	E2SM_NI_NI_Type_t	 interface_type;
	struct E2SM_NI_E2SM_NI_RANfunction_Item__ric_EventTriggerStyle_List {
		A_SEQUENCE_OF(struct E2SM_NI_RIC_EventTriggerStyle_List) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ric_EventTriggerStyle_List;
	struct E2SM_NI_E2SM_NI_RANfunction_Item__ric_ReportStyle_List {
		A_SEQUENCE_OF(struct E2SM_NI_RIC_ReportStyle_List) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ric_ReportStyle_List;
	struct E2SM_NI_E2SM_NI_RANfunction_Item__ric_InsertStyle_List {
		A_SEQUENCE_OF(struct E2SM_NI_RIC_InsertStyle_List) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ric_InsertStyle_List;
	struct E2SM_NI_E2SM_NI_RANfunction_Item__ric_ControlStyle_List {
		A_SEQUENCE_OF(struct E2SM_NI_RIC_ControlStyle_List) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ric_ControlStyle_List;
	struct E2SM_NI_E2SM_NI_RANfunction_Item__ric_PolicyStyle_List {
		A_SEQUENCE_OF(struct E2SM_NI_RIC_PolicyStyle_List) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ric_PolicyStyle_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_NI_E2SM_NI_RANfunction_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_NI_E2SM_NI_RANfunction_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_E2SM_NI_E2SM_NI_RANfunction_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_E2SM_NI_E2SM_NI_RANfunction_Item_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_NI_E2SM_NI_RANfunction_Item_H_ */
#include "asn_internal.h"
