/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Descriptions"
 * 	found in "./e2ap-v01.01.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D E2AP-v01.01/`
 */

#ifndef	_E2AP_SuccessfulOutcome_H_
#define	_E2AP_SuccessfulOutcome_H_


#include "asn_application.h"

/* Including external dependencies */
#include "E2AP_ProcedureCode.h"
#include "E2AP_Criticality.h"
#include "ANY.h"
#include "asn_ioc.h"
#include "E2AP_RICsubscriptionRequest.h"
#include "E2AP_RICsubscriptionResponse.h"
#include "E2AP_RICsubscriptionFailure.h"
#include "E2AP_RICsubscriptionDeleteRequest.h"
#include "E2AP_RICsubscriptionDeleteResponse.h"
#include "E2AP_RICsubscriptionDeleteFailure.h"
#include "E2AP_RICserviceUpdate.h"
#include "E2AP_RICserviceUpdateAcknowledge.h"
#include "E2AP_RICserviceUpdateFailure.h"
#include "E2AP_RICcontrolRequest.h"
#include "E2AP_RICcontrolAcknowledge.h"
#include "E2AP_RICcontrolFailure.h"
#include "E2AP_E2setupRequest.h"
#include "E2AP_E2setupResponse.h"
#include "E2AP_E2setupFailure.h"
#include "E2AP_E2nodeConfigurationUpdate.h"
#include "E2AP_E2nodeConfigurationUpdateAcknowledge.h"
#include "E2AP_E2nodeConfigurationUpdateFailure.h"
#include "E2AP_E2connectionUpdate.h"
#include "E2AP_E2connectionUpdateAcknowledge.h"
#include "E2AP_E2connectionUpdateFailure.h"
#include "E2AP_ResetRequest.h"
#include "E2AP_ResetResponse.h"
#include "E2AP_RICindication.h"
#include "E2AP_RICserviceQuery.h"
#include "E2AP_ErrorIndication.h"
#include "OPEN_TYPE.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2AP_SuccessfulOutcome__value_PR {
	E2AP_SuccessfulOutcome__value_PR_NOTHING,	/* No components present */
	E2AP_SuccessfulOutcome__value_PR_RICsubscriptionResponse,
	E2AP_SuccessfulOutcome__value_PR_RICsubscriptionDeleteResponse,
	E2AP_SuccessfulOutcome__value_PR_RICserviceUpdateAcknowledge,
	E2AP_SuccessfulOutcome__value_PR_RICcontrolAcknowledge,
	E2AP_SuccessfulOutcome__value_PR_E2setupResponse,
	E2AP_SuccessfulOutcome__value_PR_E2nodeConfigurationUpdateAcknowledge,
	E2AP_SuccessfulOutcome__value_PR_E2connectionUpdateAcknowledge,
	E2AP_SuccessfulOutcome__value_PR_ResetResponse
} E2AP_SuccessfulOutcome__value_PR;

/* E2AP_SuccessfulOutcome */
typedef struct E2AP_SuccessfulOutcome {
	E2AP_ProcedureCode_t	 procedureCode;
	E2AP_Criticality_t	 criticality;
	struct E2AP_SuccessfulOutcome__value {
		E2AP_SuccessfulOutcome__value_PR present;
		union E2AP_SuccessfulOutcome__E2AP_value_u {
			E2AP_RICsubscriptionResponse_t	 RICsubscriptionResponse;
			E2AP_RICsubscriptionDeleteResponse_t	 RICsubscriptionDeleteResponse;
			E2AP_RICserviceUpdateAcknowledge_t	 RICserviceUpdateAcknowledge;
			E2AP_RICcontrolAcknowledge_t	 RICcontrolAcknowledge;
			E2AP_E2setupResponse_t	 E2setupResponse;
			E2AP_E2nodeConfigurationUpdateAcknowledge_t	 E2nodeConfigurationUpdateAcknowledge;
			E2AP_E2connectionUpdateAcknowledge_t	 E2connectionUpdateAcknowledge;
			E2AP_ResetResponse_t	 ResetResponse;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_SuccessfulOutcome_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2AP_SuccessfulOutcome;
extern asn_SEQUENCE_specifics_t asn_SPC_E2AP_SuccessfulOutcome_specs_1;
extern asn_TYPE_member_t asn_MBR_E2AP_SuccessfulOutcome_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _E2AP_SuccessfulOutcome_H_ */
#include "asn_internal.h"
