/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-CommonDataTypes"
 * 	found in "./e2ap-v01.01.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D E2AP-v01.01/`
 */

#ifndef	_E2AP_ProcedureCode_H_
#define	_E2AP_ProcedureCode_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* E2AP_ProcedureCode */
typedef long	 E2AP_ProcedureCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E2AP_ProcedureCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProcedureCode;
asn_struct_free_f E2AP_ProcedureCode_free;
asn_struct_print_f E2AP_ProcedureCode_print;
asn_constr_check_f E2AP_ProcedureCode_constraint;
ber_type_decoder_f E2AP_ProcedureCode_decode_ber;
der_type_encoder_f E2AP_ProcedureCode_encode_der;
xer_type_decoder_f E2AP_ProcedureCode_decode_xer;
xer_type_encoder_f E2AP_ProcedureCode_encode_xer;
per_type_decoder_f E2AP_ProcedureCode_decode_uper;
per_type_encoder_f E2AP_ProcedureCode_encode_uper;
per_type_decoder_f E2AP_ProcedureCode_decode_aper;
per_type_encoder_f E2AP_ProcedureCode_encode_aper;
#define E2AP_ProcedureCode_id_E2setup	((E2AP_ProcedureCode_t)1)
#define E2AP_ProcedureCode_id_ErrorIndication	((E2AP_ProcedureCode_t)2)
#define E2AP_ProcedureCode_id_Reset	((E2AP_ProcedureCode_t)3)
#define E2AP_ProcedureCode_id_RICcontrol	((E2AP_ProcedureCode_t)4)
#define E2AP_ProcedureCode_id_RICindication	((E2AP_ProcedureCode_t)5)
#define E2AP_ProcedureCode_id_RICserviceQuery	((E2AP_ProcedureCode_t)6)
#define E2AP_ProcedureCode_id_RICserviceUpdate	((E2AP_ProcedureCode_t)7)
#define E2AP_ProcedureCode_id_RICsubscription	((E2AP_ProcedureCode_t)8)
#define E2AP_ProcedureCode_id_RICsubscriptionDelete	((E2AP_ProcedureCode_t)9)
#define E2AP_ProcedureCode_id_E2nodeConfigurationUpdate	((E2AP_ProcedureCode_t)10)
#define E2AP_ProcedureCode_id_E2connectionUpdate	((E2AP_ProcedureCode_t)11)

#ifdef __cplusplus
}
#endif

#endif	/* _E2AP_ProcedureCode_H_ */
#include "asn_internal.h"
