/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "./e2ap-v01.01.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D E2AP-v01.01/`
 */

#ifndef	_E2AP_E2nodeComponentConfigUpdate_H_
#define	_E2AP_E2nodeComponentConfigUpdate_H_


#include "asn_application.h"

/* Including external dependencies */
#include "E2AP_E2nodeComponentConfigUpdateGNB.h"
#include "E2AP_E2nodeComponentConfigUpdateENgNB.h"
#include "E2AP_E2nodeComponentConfigUpdateNGeNB.h"
#include "E2AP_E2nodeComponentConfigUpdateENB.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2AP_E2nodeComponentConfigUpdate_PR {
	E2AP_E2nodeComponentConfigUpdate_PR_NOTHING,	/* No components present */
	E2AP_E2nodeComponentConfigUpdate_PR_gNBconfigUpdate,
	E2AP_E2nodeComponentConfigUpdate_PR_en_gNBconfigUpdate,
	E2AP_E2nodeComponentConfigUpdate_PR_ng_eNBconfigUpdate,
	E2AP_E2nodeComponentConfigUpdate_PR_eNBconfigUpdate
	/* Extensions may appear below */
	
} E2AP_E2nodeComponentConfigUpdate_PR;

/* E2AP_E2nodeComponentConfigUpdate */
typedef struct E2AP_E2nodeComponentConfigUpdate {
	E2AP_E2nodeComponentConfigUpdate_PR present;
	union E2AP_E2nodeComponentConfigUpdate_u {
		E2AP_E2nodeComponentConfigUpdateGNB_t	 gNBconfigUpdate;
		E2AP_E2nodeComponentConfigUpdateENgNB_t	 en_gNBconfigUpdate;
		E2AP_E2nodeComponentConfigUpdateNGeNB_t	 ng_eNBconfigUpdate;
		E2AP_E2nodeComponentConfigUpdateENB_t	 eNBconfigUpdate;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_E2nodeComponentConfigUpdate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2AP_E2nodeComponentConfigUpdate;
extern asn_CHOICE_specifics_t asn_SPC_E2AP_E2nodeComponentConfigUpdate_specs_1;
extern asn_TYPE_member_t asn_MBR_E2AP_E2nodeComponentConfigUpdate_1[4];
extern asn_per_constraints_t asn_PER_type_E2AP_E2nodeComponentConfigUpdate_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _E2AP_E2nodeComponentConfigUpdate_H_ */
#include "asn_internal.h"
