/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-Containers"
 * 	found in "./e2ap-v01.01.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D E2AP-v01.01/`
 */

#ifndef	_E2AP_ProtocolIE_Container_H_
#define	_E2AP_ProtocolIE_Container_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E2AP_RICsubscriptionRequest_IEs;
struct E2AP_RICsubscriptionResponse_IEs;
struct E2AP_RICsubscriptionFailure_IEs;
struct E2AP_RICsubscriptionDeleteRequest_IEs;
struct E2AP_RICsubscriptionDeleteResponse_IEs;
struct E2AP_RICsubscriptionDeleteFailure_IEs;
struct E2AP_RICindication_IEs;
struct E2AP_RICcontrolRequest_IEs;
struct E2AP_RICcontrolAcknowledge_IEs;
struct E2AP_RICcontrolFailure_IEs;
struct E2AP_ErrorIndication_IEs;
struct E2AP_E2setupRequestIEs;
struct E2AP_E2setupResponseIEs;
struct E2AP_E2setupFailureIEs;
struct E2AP_E2connectionUpdate_IEs;
struct E2AP_E2connectionUpdateAck_IEs;
struct E2AP_E2connectionUpdateFailure_IEs;
struct E2AP_E2nodeConfigurationUpdate_IEs;
struct E2AP_E2nodeConfigurationUpdateAcknowledge_IEs;
struct E2AP_E2nodeConfigurationUpdateFailure_IEs;
struct E2AP_ResetRequestIEs;
struct E2AP_ResetResponseIEs;
struct E2AP_RICserviceUpdate_IEs;
struct E2AP_RICserviceUpdateAcknowledge_IEs;
struct E2AP_RICserviceUpdateFailure_IEs;
struct E2AP_RICserviceQuery_IEs;

/* E2AP_ProtocolIE-Container */
typedef struct E2AP_ProtocolIE_Container_1709P0 {
	A_SEQUENCE_OF(struct E2AP_RICsubscriptionRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P0_t;
typedef struct E2AP_ProtocolIE_Container_1709P1 {
	A_SEQUENCE_OF(struct E2AP_RICsubscriptionResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P1_t;
typedef struct E2AP_ProtocolIE_Container_1709P2 {
	A_SEQUENCE_OF(struct E2AP_RICsubscriptionFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P2_t;
typedef struct E2AP_ProtocolIE_Container_1709P3 {
	A_SEQUENCE_OF(struct E2AP_RICsubscriptionDeleteRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P3_t;
typedef struct E2AP_ProtocolIE_Container_1709P4 {
	A_SEQUENCE_OF(struct E2AP_RICsubscriptionDeleteResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P4_t;
typedef struct E2AP_ProtocolIE_Container_1709P5 {
	A_SEQUENCE_OF(struct E2AP_RICsubscriptionDeleteFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P5_t;
typedef struct E2AP_ProtocolIE_Container_1709P6 {
	A_SEQUENCE_OF(struct E2AP_RICindication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P6_t;
typedef struct E2AP_ProtocolIE_Container_1709P7 {
	A_SEQUENCE_OF(struct E2AP_RICcontrolRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P7_t;
typedef struct E2AP_ProtocolIE_Container_1709P8 {
	A_SEQUENCE_OF(struct E2AP_RICcontrolAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P8_t;
typedef struct E2AP_ProtocolIE_Container_1709P9 {
	A_SEQUENCE_OF(struct E2AP_RICcontrolFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P9_t;
typedef struct E2AP_ProtocolIE_Container_1709P10 {
	A_SEQUENCE_OF(struct E2AP_ErrorIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P10_t;
typedef struct E2AP_ProtocolIE_Container_1709P11 {
	A_SEQUENCE_OF(struct E2AP_E2setupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P11_t;
typedef struct E2AP_ProtocolIE_Container_1709P12 {
	A_SEQUENCE_OF(struct E2AP_E2setupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P12_t;
typedef struct E2AP_ProtocolIE_Container_1709P13 {
	A_SEQUENCE_OF(struct E2AP_E2setupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P13_t;
typedef struct E2AP_ProtocolIE_Container_1709P14 {
	A_SEQUENCE_OF(struct E2AP_E2connectionUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P14_t;
typedef struct E2AP_ProtocolIE_Container_1709P15 {
	A_SEQUENCE_OF(struct E2AP_E2connectionUpdateAck_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P15_t;
typedef struct E2AP_ProtocolIE_Container_1709P16 {
	A_SEQUENCE_OF(struct E2AP_E2connectionUpdateFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P16_t;
typedef struct E2AP_ProtocolIE_Container_1709P17 {
	A_SEQUENCE_OF(struct E2AP_E2nodeConfigurationUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P17_t;
typedef struct E2AP_ProtocolIE_Container_1709P18 {
	A_SEQUENCE_OF(struct E2AP_E2nodeConfigurationUpdateAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P18_t;
typedef struct E2AP_ProtocolIE_Container_1709P19 {
	A_SEQUENCE_OF(struct E2AP_E2nodeConfigurationUpdateFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P19_t;
typedef struct E2AP_ProtocolIE_Container_1709P20 {
	A_SEQUENCE_OF(struct E2AP_ResetRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P20_t;
typedef struct E2AP_ProtocolIE_Container_1709P21 {
	A_SEQUENCE_OF(struct E2AP_ResetResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P21_t;
typedef struct E2AP_ProtocolIE_Container_1709P22 {
	A_SEQUENCE_OF(struct E2AP_RICserviceUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P22_t;
typedef struct E2AP_ProtocolIE_Container_1709P23 {
	A_SEQUENCE_OF(struct E2AP_RICserviceUpdateAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P23_t;
typedef struct E2AP_ProtocolIE_Container_1709P24 {
	A_SEQUENCE_OF(struct E2AP_RICserviceUpdateFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P24_t;
typedef struct E2AP_ProtocolIE_Container_1709P25 {
	A_SEQUENCE_OF(struct E2AP_RICserviceQuery_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2AP_ProtocolIE_Container_1709P25_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P0;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P0_specs_1;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P0_1[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P1;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P1_specs_3;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P1_3[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P2;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P2_specs_5;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P2_5[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P3;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P3_specs_7;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P3_7[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P4;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P4_specs_9;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P4_9[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P5;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P5_specs_11;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P5_11[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P6;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P6_specs_13;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P6_13[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P7;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P7_specs_15;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P7_15[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P8;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P8_specs_17;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P8_17[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P9;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P9_specs_19;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P9_19[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P10;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P10_specs_21;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P10_21[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P11;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P11_specs_23;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P11_23[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P12;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P12_specs_25;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P12_25[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P13;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P13_specs_27;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P13_27[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P14;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P14_specs_29;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P14_29[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P15;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P15_specs_31;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P15_31[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P16;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P16_specs_33;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P16_33[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P17;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P17_specs_35;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P17_35[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P18;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P18_specs_37;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P18_37[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P19;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P19_specs_39;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P19_39[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P20;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P20_specs_41;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P20_41[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P21;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P21_specs_43;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P21_43[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P22;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P22_specs_45;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P22_45[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P23;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P23_specs_47;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P23_47[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P24;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P24_specs_49;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P24_49[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1709P25;
extern asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1709P25_specs_51;
extern asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1709P25_51[1];
extern asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1709P25_constr_51;

#ifdef __cplusplus
}
#endif

#endif	/* _E2AP_ProtocolIE_Container_H_ */
#include "asn_internal.h"
