/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "./e2ap-v01.01.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D E2AP-v01.01/`
 */

#ifndef	_E2AP_CauseRIC_H_
#define	_E2AP_CauseRIC_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2AP_CauseRIC {
	E2AP_CauseRIC_ran_function_id_Invalid	= 0,
	E2AP_CauseRIC_action_not_supported	= 1,
	E2AP_CauseRIC_excessive_actions	= 2,
	E2AP_CauseRIC_duplicate_action	= 3,
	E2AP_CauseRIC_duplicate_event	= 4,
	E2AP_CauseRIC_function_resource_limit	= 5,
	E2AP_CauseRIC_request_id_unknown	= 6,
	E2AP_CauseRIC_inconsistent_action_subsequent_action_sequence	= 7,
	E2AP_CauseRIC_control_message_invalid	= 8,
	E2AP_CauseRIC_call_process_id_invalid	= 9,
	E2AP_CauseRIC_unspecified	= 10
	/*
	 * Enumeration is extensible
	 */
} e_E2AP_CauseRIC;

/* E2AP_CauseRIC */
typedef long	 E2AP_CauseRIC_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E2AP_CauseRIC_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E2AP_CauseRIC;
extern const asn_INTEGER_specifics_t asn_SPC_E2AP_CauseRIC_specs_1;
asn_struct_free_f E2AP_CauseRIC_free;
asn_struct_print_f E2AP_CauseRIC_print;
asn_constr_check_f E2AP_CauseRIC_constraint;
ber_type_decoder_f E2AP_CauseRIC_decode_ber;
der_type_encoder_f E2AP_CauseRIC_encode_der;
xer_type_decoder_f E2AP_CauseRIC_decode_xer;
xer_type_encoder_f E2AP_CauseRIC_encode_xer;
per_type_decoder_f E2AP_CauseRIC_decode_uper;
per_type_encoder_f E2AP_CauseRIC_encode_uper;
per_type_decoder_f E2AP_CauseRIC_decode_aper;
per_type_encoder_f E2AP_CauseRIC_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E2AP_CauseRIC_H_ */
#include "asn_internal.h"
