/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-NI-IEs"
 * 	found in "/local/mnt/openairinterface5g/openair2/RIC_AGENT/MESSAGES/ASN1/R01/e2sm-ni-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/mnt/openairinterface5g/cmake_targets/ran_build/build/CMakeFiles/E2SM-NI/`
 */

#ifndef	_E2SM_NI_RANparameter_Value_H_
#define	_E2SM_NI_RANparameter_Value_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "BOOLEAN.h"
#include "BIT_STRING.h"
#include "OCTET_STRING.h"
#include "PrintableString.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2SM_NI_RANparameter_Value_PR {
	E2SM_NI_RANparameter_Value_PR_NOTHING,	/* No components present */
	E2SM_NI_RANparameter_Value_PR_valueInt,
	E2SM_NI_RANparameter_Value_PR_valueEnum,
	E2SM_NI_RANparameter_Value_PR_valueBool,
	E2SM_NI_RANparameter_Value_PR_valueBitS,
	E2SM_NI_RANparameter_Value_PR_valueOctS,
	E2SM_NI_RANparameter_Value_PR_valuePrtS
	/* Extensions may appear below */
	
} E2SM_NI_RANparameter_Value_PR;

/* E2SM_NI_RANparameter-Value */
typedef struct E2SM_NI_RANparameter_Value {
	E2SM_NI_RANparameter_Value_PR present;
	union E2SM_NI_RANparameter_Value_u {
		long	 valueInt;
		long	 valueEnum;
		BOOLEAN_t	 valueBool;
		BIT_STRING_t	 valueBitS;
		OCTET_STRING_t	 valueOctS;
		PrintableString_t	 valuePrtS;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_NI_RANparameter_Value_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_NI_RANparameter_Value;
extern asn_CHOICE_specifics_t asn_SPC_E2SM_NI_RANparameter_Value_specs_1;
extern asn_TYPE_member_t asn_MBR_E2SM_NI_RANparameter_Value_1[6];
extern asn_per_constraints_t asn_PER_type_E2SM_NI_RANparameter_Value_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_NI_RANparameter_Value_H_ */
#include "asn_internal.h"
