/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-NI-IEs"
 * 	found in "/local/mnt/openairinterface5g/openair2/RIC_AGENT/MESSAGES/ASN1/R01/e2sm-ni-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/mnt/openairinterface5g/cmake_targets/ran_build/build/CMakeFiles/E2SM-NI/`
 */

#ifndef	_E2SM_NI_NI_MessageType_H_
#define	_E2SM_NI_NI_MessageType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "E2SM_NI_NI-MessageTypeS1.h"
#include "E2SM_NI_NI-MessageTypeX2.h"
#include "E2SM_NI_NI-MessageTypeNG.h"
#include "E2SM_NI_NI-MessageTypeXn.h"
#include "E2SM_NI_NI-MessageTypeF1.h"
#include "E2SM_NI_NI-MessageTypeE1.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2SM_NI_NI_MessageType_PR {
	E2SM_NI_NI_MessageType_PR_NOTHING,	/* No components present */
	E2SM_NI_NI_MessageType_PR_s1MessageType,
	E2SM_NI_NI_MessageType_PR_x2MessageType,
	E2SM_NI_NI_MessageType_PR_ngMessageType,
	E2SM_NI_NI_MessageType_PR_xnMessageType,
	E2SM_NI_NI_MessageType_PR_f1MessageType,
	E2SM_NI_NI_MessageType_PR_e1MessageType
	/* Extensions may appear below */
	
} E2SM_NI_NI_MessageType_PR;

/* E2SM_NI_NI-MessageType */
typedef struct E2SM_NI_NI_MessageType {
	E2SM_NI_NI_MessageType_PR present;
	union E2SM_NI_NI_MessageType_u {
		E2SM_NI_NI_MessageTypeS1_t	 s1MessageType;
		E2SM_NI_NI_MessageTypeX2_t	 x2MessageType;
		E2SM_NI_NI_MessageTypeNG_t	 ngMessageType;
		E2SM_NI_NI_MessageTypeXn_t	 xnMessageType;
		E2SM_NI_NI_MessageTypeF1_t	 f1MessageType;
		E2SM_NI_NI_MessageTypeE1_t	 e1MessageType;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_NI_NI_MessageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_NI_NI_MessageType;
extern asn_CHOICE_specifics_t asn_SPC_E2SM_NI_NI_MessageType_specs_1;
extern asn_TYPE_member_t asn_MBR_E2SM_NI_NI_MessageType_1[6];
extern asn_per_constraints_t asn_PER_type_E2SM_NI_NI_MessageType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_NI_NI_MessageType_H_ */
#include "asn_internal.h"
