/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _E2SM_NI_ASN_CONSTANT_H
#define _E2SM_NI_ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define min_val_E2SM_NI_GNB_CU_UP_ID (0)
#define max_val_E2SM_NI_GNB_CU_UP_ID (68719476735)
#define min_val_E2SM_NI_GNB_DU_ID (0)
#define max_val_E2SM_NI_GNB_DU_ID (68719476735)
#define E2SM_NI_maxProtocolIEs (65535)
#define min_val_E2SM_NI_ProcedureCode (0)
#define max_val_E2SM_NI_ProcedureCode (255)
#define min_val_E2SM_NI_ProtocolIE_ID (0)
#define max_val_E2SM_NI_ProtocolIE_ID (65535)
#define E2SM_NI_maxofInterfaceProtocolTests (15)
#define E2SM_NI_maxofRANueGroups (255)
#define E2SM_NI_maxofActionParameters (255)
#define E2SM_NI_maxofRANparameters (65535)
#define E2SM_NI_maxofNItypes (63)
#define E2SM_NI_maxofRICstyles (63)
#define min_val_E2SM_NI_RANparameter_ID (0)
#define max_val_E2SM_NI_RANparameter_ID (65535)
#define min_val_E2SM_NI_RANueGroupID (0)
#define max_val_E2SM_NI_RANueGroupID (255)


#ifdef __cplusplus
}
#endif

#endif /* _E2SM_NI_ASN_CONSTANT_H */
