/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-Containers"
 * 	found in "/local/mnt/openairinterface5g/openair2/RIC_AGENT/MESSAGES/ASN1/R01/e2ap-v01.00.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -fincludes-quoted -D /local/mnt/openairinterface5g/cmake_targets/ran_build/build/CMakeFiles/E2AP/`
 */

#include "E2AP_ProtocolIE-Container.h"

#include "E2AP_ProtocolIE-Field.h"
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P0_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P1_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P2_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P3_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P4_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P5_constr_11 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P6_constr_13 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P7_constr_15 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P8_constr_17 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P9_constr_19 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P10_constr_21 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P11_constr_23 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P12_constr_25 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P13_constr_27 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P14_constr_29 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P15_constr_31 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P16_constr_33 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P17_constr_35 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P18_constr_37 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2AP_ProtocolIE_Container_1389P19_constr_39 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P0_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_RICsubscriptionRequest_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P0_specs_1 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P0),
	offsetof(struct E2AP_ProtocolIE_Container_1389P0, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P0 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P0_tags_1,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P0_tags_1)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P0_tags_1[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P0_tags_1)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P0_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P0_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P0_1,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P0_specs_1	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P1_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_RICsubscriptionResponse_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P1_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P1_specs_3 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P1),
	offsetof(struct E2AP_ProtocolIE_Container_1389P1, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P1 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P1_tags_3,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P1_tags_3)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P1_tags_3[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P1_tags_3,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P1_tags_3)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P1_tags_3[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P1_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P1_3,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P1_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P2_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_RICsubscriptionFailure_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P2_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P2_specs_5 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P2),
	offsetof(struct E2AP_ProtocolIE_Container_1389P2, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P2 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P2_tags_5,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P2_tags_5)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P2_tags_5[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P2_tags_5,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P2_tags_5)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P2_tags_5[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P2_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P2_5,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P2_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P3_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_RICsubscriptionDeleteRequest_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P3_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P3_specs_7 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P3),
	offsetof(struct E2AP_ProtocolIE_Container_1389P3, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P3 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P3_tags_7,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P3_tags_7)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P3_tags_7[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P3_tags_7,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P3_tags_7)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P3_tags_7[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P3_constr_7, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P3_7,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P3_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P4_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_RICsubscriptionDeleteResponse_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P4_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P4_specs_9 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P4),
	offsetof(struct E2AP_ProtocolIE_Container_1389P4, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P4 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P4_tags_9,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P4_tags_9)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P4_tags_9[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P4_tags_9,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P4_tags_9)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P4_tags_9[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P4_constr_9, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P4_9,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P4_specs_9	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P5_11[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_RICsubscriptionDeleteFailure_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P5_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P5_specs_11 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P5),
	offsetof(struct E2AP_ProtocolIE_Container_1389P5, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P5 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P5_tags_11,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P5_tags_11)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P5_tags_11[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P5_tags_11,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P5_tags_11)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P5_tags_11[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P5_constr_11, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P5_11,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P5_specs_11	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P6_13[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_RICindication_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P6_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P6_specs_13 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P6),
	offsetof(struct E2AP_ProtocolIE_Container_1389P6, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P6 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P6_tags_13,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P6_tags_13)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P6_tags_13[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P6_tags_13,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P6_tags_13)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P6_tags_13[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P6_constr_13, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P6_13,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P6_specs_13	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P7_15[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_RICcontrolRequest_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P7_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P7_specs_15 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P7),
	offsetof(struct E2AP_ProtocolIE_Container_1389P7, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P7 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P7_tags_15,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P7_tags_15)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P7_tags_15[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P7_tags_15,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P7_tags_15)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P7_tags_15[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P7_constr_15, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P7_15,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P7_specs_15	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P8_17[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_RICcontrolAcknowledge_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P8_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P8_specs_17 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P8),
	offsetof(struct E2AP_ProtocolIE_Container_1389P8, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P8 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P8_tags_17,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P8_tags_17)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P8_tags_17[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P8_tags_17,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P8_tags_17)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P8_tags_17[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P8_constr_17, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P8_17,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P8_specs_17	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P9_19[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_RICcontrolFailure_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P9_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P9_specs_19 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P9),
	offsetof(struct E2AP_ProtocolIE_Container_1389P9, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P9 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P9_tags_19,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P9_tags_19)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P9_tags_19[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P9_tags_19,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P9_tags_19)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P9_tags_19[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P9_constr_19, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P9_19,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P9_specs_19	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P10_21[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_ErrorIndication_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P10_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P10_specs_21 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P10),
	offsetof(struct E2AP_ProtocolIE_Container_1389P10, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P10 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P10_tags_21,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P10_tags_21)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P10_tags_21[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P10_tags_21,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P10_tags_21)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P10_tags_21[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P10_constr_21, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P10_21,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P10_specs_21	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P11_23[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_E2setupRequestIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P11_tags_23[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P11_specs_23 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P11),
	offsetof(struct E2AP_ProtocolIE_Container_1389P11, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P11 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P11_tags_23,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P11_tags_23)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P11_tags_23[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P11_tags_23,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P11_tags_23)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P11_tags_23[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P11_constr_23, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P11_23,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P11_specs_23	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P12_25[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_E2setupResponseIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P12_tags_25[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P12_specs_25 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P12),
	offsetof(struct E2AP_ProtocolIE_Container_1389P12, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P12 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P12_tags_25,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P12_tags_25)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P12_tags_25[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P12_tags_25,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P12_tags_25)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P12_tags_25[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P12_constr_25, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P12_25,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P12_specs_25	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P13_27[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_E2setupFailureIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P13_tags_27[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P13_specs_27 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P13),
	offsetof(struct E2AP_ProtocolIE_Container_1389P13, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P13 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P13_tags_27,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P13_tags_27)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P13_tags_27[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P13_tags_27,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P13_tags_27)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P13_tags_27[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P13_constr_27, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P13_27,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P13_specs_27	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P14_29[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_ResetRequestIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P14_tags_29[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P14_specs_29 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P14),
	offsetof(struct E2AP_ProtocolIE_Container_1389P14, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P14 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P14_tags_29,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P14_tags_29)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P14_tags_29[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P14_tags_29,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P14_tags_29)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P14_tags_29[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P14_constr_29, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P14_29,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P14_specs_29	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P15_31[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_ResetResponseIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P15_tags_31[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P15_specs_31 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P15),
	offsetof(struct E2AP_ProtocolIE_Container_1389P15, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P15 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P15_tags_31,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P15_tags_31)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P15_tags_31[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P15_tags_31,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P15_tags_31)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P15_tags_31[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P15_constr_31, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P15_31,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P15_specs_31	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P16_33[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_RICserviceUpdate_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P16_tags_33[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P16_specs_33 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P16),
	offsetof(struct E2AP_ProtocolIE_Container_1389P16, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P16 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P16_tags_33,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P16_tags_33)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P16_tags_33[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P16_tags_33,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P16_tags_33)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P16_tags_33[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P16_constr_33, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P16_33,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P16_specs_33	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P17_35[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_RICserviceUpdateAcknowledge_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P17_tags_35[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P17_specs_35 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P17),
	offsetof(struct E2AP_ProtocolIE_Container_1389P17, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P17 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P17_tags_35,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P17_tags_35)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P17_tags_35[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P17_tags_35,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P17_tags_35)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P17_tags_35[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P17_constr_35, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P17_35,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P17_specs_35	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P18_37[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_RICserviceUpdateFailure_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P18_tags_37[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P18_specs_37 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P18),
	offsetof(struct E2AP_ProtocolIE_Container_1389P18, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P18 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P18_tags_37,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P18_tags_37)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P18_tags_37[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P18_tags_37,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P18_tags_37)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P18_tags_37[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P18_constr_37, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P18_37,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P18_specs_37	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2AP_ProtocolIE_Container_1389P19_39[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2AP_RICserviceQuery_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2AP_ProtocolIE_Container_1389P19_tags_39[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2AP_ProtocolIE_Container_1389P19_specs_39 = {
	sizeof(struct E2AP_ProtocolIE_Container_1389P19),
	offsetof(struct E2AP_ProtocolIE_Container_1389P19, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2AP_ProtocolIE_Container_1389P19 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2AP_ProtocolIE_Container_1389P19_tags_39,
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P19_tags_39)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P19_tags_39[0]), /* 1 */
	asn_DEF_E2AP_ProtocolIE_Container_1389P19_tags_39,	/* Same as above */
	sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P19_tags_39)
		/sizeof(asn_DEF_E2AP_ProtocolIE_Container_1389P19_tags_39[0]), /* 1 */
	{ 0, &asn_PER_type_E2AP_ProtocolIE_Container_1389P19_constr_39, SEQUENCE_OF_constraint },
	asn_MBR_E2AP_ProtocolIE_Container_1389P19_39,
	1,	/* Single element */
	&asn_SPC_E2AP_ProtocolIE_Container_1389P19_specs_39	/* Additional specs */
};

